### ISSUE TITLE
Updating to 2.7.0 fails after update to 2.6.0 was fine

### ISSUE THREAD

**Issue by daedaevibin** [krille-chan/fluffychat#3139]
### Bug Description

build failure

### Steps to Reproduce

Standard AUR package updated (2.7.0-1)

/tmp/makepkg/fluffychat/src/fluffychat-2.7.0/linux/flutter/ephemeral/.plugin_symlinks/flutter_webrtc/linux/../third_party/libwebrtc/include/rtc_types.h:98:3: error: unknown type name 'uint32_t'
/tmp/makepkg/fluffychat/src/fluffychat-2.7.0/linux/flutter/ephemeral/.plugin_symlinks/flutter_webrtc/linux/../third_party/libwebrtc/include/rtc_types.h:99:3: error: unknown type name 'uint32_t'

### Expected Behavior

Build and install.

### App Version

7.2.0

### Platform

Linux (Other)

### Additional Platform Information

CachyOS Linux x86_84(v3)

### Additional Context

I am unsure who maintains the AUR package or if it is official.

Name: fluffychat

**Comment by xiota** [comment]
I'm the maintainer of the AUR package.  It's not official, and nothing on AUR should be considered to be.

The AUR package has been updated with a workaround.  It's heavy handed because I was unable to find a targeted fix.

**Comment by daedaevibin** [comment]
> I'm the maintainer of the AUR package.  It's not official, and nothing on AUR should be considered to be.
> 
> The AUR package has been updated with a workaround.  It's heavy handed because I was unable to find a targeted fix.

Yes, my apologies.

I meant to come back here to close this since you responded over at the AUR, but I got rather busy.

Thanks for your work and assistance!

**Comment by xiota** [comment]
Would make sense to leave this issue open until upstream has a chance to look for the cause.

**Comment by krille-chan** [comment]
so I've no idea :-( building for snapcraft, flatpak and also compiling a normal tar file works. I'm not maintaining the AUR package but if you have any specific questions, don't hesitate to ask <3

**Comment by xiota** [comment]
Recent releases of GCC and Clang have been more strict about missing standard headers.  GitHub workflows won't be affected if they're using older versions.  The fix would be to add `#include <cstdint>` to `rtc_types.h`, but I don't see how it's generated.  Maybe in [flutter-webrtc](https://github.com/flutter-webrtc/flutter-webrtc)?
